### ISSUE TITLE
Post authorship?

### ISSUE THREAD

**Issue by mattansb** [easystats/blog#24]
What do we think of having post's author's name attached to the blog post? 
(Not in a vain kind of way, just in an informative one - but I'm totally cool with this not even being on the table :grinning: )

**Comment by DominiqueMakowski** [comment]
it's a good question. For blog posts specifically, there is a technical limitation in the sense that I have the impression that the "author" YAML field doesn't change anything (it is not displayed on the blog nor on r bloggers) ^^

that being said, I think that having individual names everywhere is a bit counterintuitive in regards to the organisation and its collaborative spirit (otherwise we would have not put the packages under a common entity). that's probably why you won't see @author fields in Daniel's or my functions. And also because it's somewhat true that we all in some way contributed to making the ecosystem what it is, either by code or comments or suggestions or simply by motivating or triggering the idea or encouraging :)

That being said, we (Daniel correct me if I'm wrong) don't really mind if other members do put their names in their creations, as I understand it can be useful for justifying academic achievements (if you're a PhD for instance ;). So please go ahead with however you feel.

anyway I think our opinion will have to adapt depending on how the ecosystem grows :) 

to come back to the blog post, IMO you could either leave the post "as is" but reference it in your CV or website under your personal "online teaching material". After all, what is good with github is that is includes full traceability, so everyone who wants to do so can see who contributed and how. Or you can include somewhere an "Author: ..." in the post :)

**Comment by mattansb** [comment]
> I have the impression that the "author" YAML field doesn't change anything

Good point 😅

> ... reference it in your CV or website under your personal "online teaching material"

I think that's what I'll do.

Thanks @DominiqueMakowski !

**Comment by strengejacke** [comment]
I second all being said by Dominique!
