### ISSUE TITLE
bayestestR

### ISSUE THREAD

**Issue by strengejacke** [easystats/blog#8]
Now that bayestestR is on CRAN, maybe we can publish a blog post? I really like the readme-file, actually, we could almost copy/paste that as a first post.

**Comment by DominiqueMakowski** [comment]
That's a good idea! In fact, we might even think of doing several posts. For instance, the first one could be devoted to HDI (what it is and how to compute it), a second one to ROPE, with `rope_range`, `rope` and `equivalence_test`. Another could be related to pd and such...

As these are relatively different topics/functions, having separated blogposts might be interesting because 1) shorter posts (= more read?) and 2) more specific posts might make them more easily discoverable in the depth of internet. What do you think?

**Comment by DominiqueMakowski** [comment]
Or maybe we could start by a annoucement post, very short containing stuff like "hey bayestestR if finally on CRAN! It allows to do [list of main functions], go check it out!"

And then posts detailing features

**Comment by strengejacke** [comment]
separate blog posts would be even better, but realization often fails due to my lazyness. ;-)

**Comment by DominiqueMakowski** [comment]
I'll draft a short `bayestestR_presentation` (similar to insight's) post once the package is fully built on CRAN ;)

**Comment by DominiqueMakowski** [comment]
https://www.r-bloggers.com/describe-and-understand-bayesian-models-and-posteriors-using-bayestestr/

We're on the front page 🎉 
However, the plot doesn't show up, which is IMO due to the fact that the path upon generation of the html is relative and must be replaced by the full path. Otherwise, it works in the blog, but not if the content is copy pasted elsewhere. I don't know if that's something we have to do manually or if there is a way to have "full" paths of images directly...

**Comment by pdwaggoner** [comment]
This is exciting to see!

**Comment by strengejacke** [comment]
A bit more serious is the fact that the link to the original post does not work, because r-bloggers links to https://easystats.github.io/posts/bayestestr_presentation/ instead https://easystats.github.io/blog/posts/bayestestr_presentation/

Is this something in the setup? Haven't realized this before...

**Comment by DominiqueMakowski** [comment]
Arf me neither! [here](https://github.com/easystats/blog/blob/master/config.toml#L2) it specifies the correct URL.

Maybe this was something that the r-bloggers owner set, when he added the blog to the RSS feed?
